version: "3"
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: bunnytube
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: bunnytube
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/docker/volumes/postgresql/_data
  bunnytube-backend:
    build: ./
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://bunnytube:backend@postgres/bunnytube
    ports:
      - 8443:8443
    depends_on:
      - postgres
volumes:
  postgresql:
    external: true
